config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'enrolments#index'

  resources :enrolments
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrolment.rb
# frozen_string_literal: true

class Enrolment
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessor :user_prompt

  field :thread_id, type: String
  validates_presence_of :thread_id

  before_create :create_thread

  def create_thread
    response = client.threads.create
    self.thread_id = response['id']
  end

  def create_message
    client.messages.create(thread_id:,
                           parameters: {
                             role: 'user', # Required for manually created messages
                             content: user_prompt
                           })

    create_run
  end

  def create_run
    client.runs.create(thread_id:,
                       parameters: {
                         assistant_id:,
                         max_prompt_tokens: 256,
                         max_completion_tokens: 1024,
                         stream: proc do |chunk, _bytesize|
                                   if chunk['object'] == 'thread.message.delta'
                                     print chunk.dig('delta', 'content', 0, 'text',
                                                     'value')
                                   end
                                 end
                       })
  end

  def first_id
    messages['first_id']
  end

  def answer
    return unless first_id

    client.messages.retrieve(thread_id:, id: first_id)['content'].first['text']['value']
  end

  def messages
    @messages ||= client.messages.list(thread_id:)
  end

  def client
    @client ||= OpenAI::Client.new(log_errors: true)
  end

  def assistant_id
    'asst_2EoqXtpQIXGnOaLF8aDkgXD9'
  end

  def run
    response = client.runs.create(thread_id:,
                                  parameters: {
                                    assistant_id:,
                                    max_prompt_tokens: 256,
                                    max_completion_tokens: 16
                                  })
    response['id']
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/enrolments_controller.rb
# frozen_string_literal: true

class EnrolmentsController < ApplicationController
  before_action :load_enrolment, only: %i[edit update]
  def index
    @enrolments = Enrolment.all
  end

  def new
    @enrolment = Enrolment.new(thread_id: new_thread)
    redirect_to edit_enrolment_path(@enrolment) if @enrolment.save!
  end

  def edit; end

  def update
    @enrolment.update(enrolment_params)
    @enrolment.create_message
    redirect_to edit_enrolment_path(@enrolment)
  end

  private

  def load_enrolment
    @enrolment = Enrolment.find(params[:id])
  end

  def client
    @client ||= OpenAI::Client.new(log_errors: true)
  end

  def new_thread
    response = client.threads.create
    response['id']
  end

  def enrolment_params
    params.require(:enrolment).permit(:user_prompt)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/enrolments/_answer.html.slim
= @enrolment.answer

app/views/enrolments/edit.html.slim
h1 Edit

= form_for @enrolment do |f|
  = render partial: 'answer'
  //pre = JSON.pretty_generate(@enrolment.answer)
  //hr
  //pre = JSON.pretty_generate(@enrolment.messages)
  .mb-3
    = f.label :user_prompt, class: 'form-label'
  .mb-3 
    = f.text_field :user_prompt, class: 'form-control'
  .mb-3 
    = f.submit 'Talk', class: 'btn btn-primary'

app/views/enrolments/index.html.slim
h1 Enrolments
= link_to 'New', new_enrolment_path
ul
	- @enrolments.each do | enrolment |
		li= link_to 'Edit', edit_enrolment_path(enrolment)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeisterEder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>